### ISSUE TITLE
Create dependency list

### ISSUE THREAD

**Issue by rhiannonlynne** [lsst-sims/migration_plan#1]
We need a list of the (external, third-party) dependencies for the sims packages.

**Comment by rhiannonlynne** [comment]
numpy
pandas 
matplotlib
palpy
astropy

oorb
documenteer

**Comment by rhiannonlynne** [comment]
Not sure about things like sncosmo. 
Or george or sympy .. things that are required for sims_maf_contrib but that we may be running as standard metrics (now or shortly). 

It may be worth considering if we want to avoid a single big repo - so that metrics requiring more complex dependencies can be separated from "basics" required to just run the scheduler.

**Comment by cwwalter** [comment]
Otherone that have come up in my tests as needed as of now in the last few days ( a subset of the list I made for the RFC)

palpy
pymsql
astropy_helpers
ephem
python_extinction

**Comment by rhiannonlynne** [comment]
We'll be dropping pymssql (as part of dropping sims_catUtils). 
Palpy may be able to substitute for ephem and this is something I think we wanted for a while. 
astropy_helpers is used for sncosmo, I think. ... same with python_extinction. So I think we still need those,  but they are available on conda or condo-forge.

**Comment by rhiannonlynne** [comment]
We had briefy discussed adding Rubin-env as a  dependency or as the base environment .. I am thinking that we probably don't need or necessarily want to do this in general, but will probably need to figure out what happens when we don't specify versions of packages but do actually have a particular dependency on a version (such as sqlaclhemy). Eli suggested shimming things to work with multiple versions in limited cases, which seems reasonable, and then we may also just have short periods where things don't match (but will need to look out for these).

**Comment by cwwalter** [comment]
Oops.. sorry... I now realized I should have put the info on dependencies here. (and I now see you have python_extinction already).
