### ISSUE TITLE
configuration for model modules

### ISSUE THREAD

**Issue by rhiannonlynne** [lsst-sims/migration_plan#2]
Things like seeingModel and cloudModel will have to go away from pexConfig and probably ought to just go to a simple yaml configuration file. 
This is in line with what T&S are doing going forward, and offers simple text configuration. 
Not sure if this means we need a proper parser for yaml. Obviously, DM has something, but we'd like to avoid that dependency.
We could alternatively, just use kwarg values, but we still need to track *how* things were configured when in use. 

There are configuration issues to consider in the scheduler as well. Likely other packages too.

**Comment by yoachim** [comment]
I'm a big fan of using kwargs. Having configuration set by random text files seems very 1980's, un-pythonic, and makes things much harder to document. I think the text configs are mostly spandrels from when folks didn't want to have to learn python to run the scheduler.
